### ISSUE TITLE
Payment Gateway Won't Show Up

### ISSUE THREAD

**Issue by diablojunk** [cyberwombat/woocommerce-fastspring-payment-gateway#10]
Hi,

I tried both methods, popup and regular, but the payment gateway just wouldn't show up.

Contacted Fastspring and they couldn't figure out the issue.

Here's the product page - https://businessquant.com/product/pro-membership-3-months

Please help.

Thanks

BQ

**Comment by cyberwombat** [comment]
Have you tried all the troubleshooting methods?  https://github.com/cyberwombat/woocommerce-fastspring-payment-gateway/wiki

**Comment by diablojunk** [comment]
Yes, cyberwombat, tried all the suggestions listed there. Unable to figure out what's really causing the issue.

**Comment by cyberwombat** [comment]
I see the message "Store Not Found".  This indicates the storefront entry is not correct - Can you paste what you have in there?

See [Wiki](https://github.com/cyberwombat/woocommerce-fastspring-payment-gateway/wiki/Plugin-installation#plugin-installation) for info on this.

**Comment by diablojunk** [comment]
Yea sure, I've entered the folowing:

businessquant.test.onfastspring.com/popup-businessquant

**Comment by cyberwombat** [comment]
Ok - try latest release.  Had an issue in how it converts the url between test/prod mode.

**Comment by diablojunk** [comment]
It's working fine now.
Thanks for the speedy turnaround :)

**Comment by cyberwombat** [comment]
Great!
