### ISSUE TITLE
Linking with Products On FS?

### ISSUE THREAD

**Issue by diablojunk** [cyberwombat/woocommerce-fastspring-payment-gateway#11]
Hi, 

How do we link Woocommerce products with those on FS? I haven't been able to find this part in your documentation. Also, the plugin doesn't seem to have any fields that would allow us to enter this information.

Thx,

Piyush

**Comment by cyberwombat** [comment]
The plugin only supports checkout and does not sync products across the platforms. It does not require products or coupons to exist on the FS site - just Woo - it will take care of passing the product data on the fly.
