### ISSUE TITLE
VAT added in WooCommerce not passed to FastSpring Popup

### ISSUE THREAD

**Issue by peterStitt** [cyberwombat/woocommerce-fastspring-payment-gateway#14]
Hello. First, thank you so much for the hard work on this plugin. I have integrated it into my test site and it seems to be working well so far.

However, I was wondering if I'm missing something. In my store I calculate VAT and add it at checkout before the customer selects a payment option. If the user selects FastSpring then the amount shown in the PopUp Store is the product price excluding VAT. FastSpring then calculates the appropriate VAT and takes it out of this total. 

For example, a product of 50€ with 20% VAT shows as 60€ at checkout. In the FastSpring pop-up it shows as 50€ total (8.33€ of VAT). This means I lose 8.33€ when a customer selects FastSpring compared to other methods.

Is it possible to pass the total price (product + VAT) to FastSpring so when they do their own VAT calculations the VAT is already included. The current functionality means that anyone purchasing through FastSpring will have a discount compared to ones paying by other methods.

Thanks for you help.

**Comment by cyberwombat** [comment]
I contacted FS about calculating and passing your own taxes and this is their reply:

"_No. As the vendor of record, we are responsible for collecting taxes and remitting them to the proper authority. Therefore we must calculate them._"
