### ISSUE TITLE
Error if product is a woo-commerce variable product

### ISSUE THREAD

**Issue by h1dd3nsn1p3r** [cyberwombat/woocommerce-fastspring-payment-gateway#15]
Thank you, contributors, who are maintaining this repo.😊 

I am using FastSpring checkout for Woocommerce in my store. It was ok till I had all my products as simple woocommerce products. Later I changed them to a variable product to add different types of licence keys like ( Single site licence, Multisite licence & developer licence ). 

Here is the example: https://themebeez.com/themes/cream-magazine-pro/ 

I noticed that when somebody tries to checkout now FS window is not being displayed. I checked console & got these errors.

> fastspring-builder.min.js:3 [FastSpring API] (!) Error: Error received:  400 variation-not-found

> [FastSpring API] (!) Error: Error received:  400 empty-session

I have attached a screenshot here: https://drive.google.com/open?id=18mKib_j6x_WJkORns8IY4-ZoJ6rMb_f0

Looking for help to fix this problem. 

Thank you in advance.

Regards,
Anuj

**Comment by cyberwombat** [comment]
This is an unusual error that I have not seen - it seems to imply that FS is trying to match the info you are sending to something on their side. The plugin is meant to only have products on Woo side so I wonder if there is something in your FS that is creating a conflict. Can you contact FS and ask them? The plugin uses the Storefront Builder library and we pass encrypted product data (no variations field in there). 
I can try to replicate too - are you using any additional Woo plugin to handle the variations or is this all stock Woo?

**Comment by h1dd3nsn1p3r** [comment]
Hello @cyberwombat thank you very much for the reply. 

FS support team very wired & weak in development support. They know only to refer this plugin https://wordpress.org/plugins/fastspring/. I don't think they understand between simple checkout button & full other shopping cart integration like Woocommerce & EDD integration. 

Let me give you more information on this issue. 

1. I haven't use any external plugin to create attributes for my variable products. I created in woocommerce way from Woocommerce > products > add new product ( variable product ) > attribute > create attribute to make variations. Here is screenshot https://drive.google.com/open?id=1D_lMBEGrxxuA3SNmeWf51Y2NycFID7Cf

2. After creating attribute I went to variations & set pricing there. here is screenshot https://drive.google.com/open?id=1QQ2QDe7Lwt3Bs2A3Bit6BFAewRbJlODq

3. All set, I had FS plugin working before when my products were a simple product. I went ahead to checkout page & tried using FS checkout & got that that above error. FS popup window never launched. 

4. But I can see under my Woocommerce orders order is pending which normally happens. Here is screenshot https://drive.google.com/open?id=1vukIr6q1Aehf9FcYELidI9FCBlBvpXJ5

5. FYI I have customized woocommerce checkout page a bit to make checkout experience better. You can try to check out here https://themebeez.com/. I am using PayPal & paddle, for now, they both work great without any error. Only the FS is not working. 

@cyberwombat quick question have you tried this plugin with variable products? If you can, will you please try it in your end. I requested with FS support team but I got expected an answer from them ( To use their plugin https://wordpress.org/plugins/fastspring/ ) 👎 lol.

Thank you in advance. 

Regards,

Anuj
