### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by mumarwaqas** [cyberwombat/woocommerce-fastspring-payment-gateway#17]
Error processing checkout. Please try again.

**Comment by cyberwombat** [comment]
That's a bit vague. Ensure you are in debug mode - check out the [wiki](https://github.com/cyberwombat/woocommerce-fastspring-payment-gateway/wiki) for info - especially the Troubleshooting section. If you have done all that and still getting errors then ensure you provide me with WP/Woo versions you are using.

**Comment by mumarwaqas** [comment]
**Wordpress:**         Version 5.2.2
**WooCommerce:** Version 3.6.5

**Comment by cyberwombat** [comment]
What does your console.log show? What about your woocommerce log? I assume you have turned debug on.
