### ISSUE TITLE
API is not working => woocommerce "order cancelled"

### ISSUE THREAD

**Issue by fantazo** [cyberwombat/woocommerce-fastspring-payment-gateway#18]
Hello Yashua,

**Congratulations on this plugin. It really looks great and easy to use.**
I have a small issue with API.

I have seen your troubleshooting document, and searched google...
But I can't solve the API connection issue between Fastspring and the WP FS plugin.

Here is what I get in the "inspect element" from chrome (attached)

I repeat: the credentials for API are correct double checket, and also made new credentials and still the same. So that I need the API to get woocommerce notified about the payment and to make it completed. 

The webhook cannot be used because of the hosting .. "handshake_failure" caused by the unsupported ciphers.. And I don't know if there is another solution for the webhook than changing the hosting..

Please help me to solve this.
I would really appreciate your time and help.

Best,
Balazs

<img width="839" alt="Screenshot 2019-08-12 at 03 37 04" src="https://user-images.githubusercontent.com/54009379/62841586-987c6300-bcb2-11e9-89c9-9c7db32a3c47.png">

**Comment by cyberwombat** [comment]
Most likely the only workaround is to obtain a  n ssl certificates from a different source. I assume have seen the bottom section on ciphers in the troubleshooting wiki page at the bottom - there is a command you can run to get the ciphers you support and compare them to FS list. LetsEncrypt is a known one to have issue and you may need to go pay for a traditional one - unfortunately i don't know specifically which ones might work - you'd have to inquire with each. Its an unfortunate situation- FS tells me that they have a codebase in Java and they are somewhat locked for now in an older version that doesn't have support for many of the new ciphers. I can't even comprehend why they don't see this as a major issue to adoption and fix this.

**Comment by fantazo** [comment]
Thank you for your fast response!

You are right about FastSpring - they are good but they should move and take these important steps and make payment integration much more simple. 

I have PositiveSSL certificate. Maybe this could be the problem?
Is there a way to integrate anything into the certificate to work?

Or is there a solution with Zapier to woocommerce or any trigger app to make a notification to the woocommerce and change the order to "completed"?

Many thanks for your help!
Best,
Balazs

**Comment by cyberwombat** [comment]
Are you able to run this command  (changing to your domain of course)
`nmap --script ssl-enum-ciphers -p 443 YOURDOMAINHERE.COM`
If you can paste the output

**Comment by fantazo** [comment]
The problem is that i don't really understand how and where to run such command..
I have tried in terminal but no results..

can you help me please?

**Comment by fantazo** [comment]
I have used this website:
https://www.ssllabs.com/ssltest/analyze.html?d=fantazo-design.com

Cipher Suites
# TLS 1.2 (suites in server-preferred order)
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)   ECDH secp256r1 (eq. 3072 bits RSA)   FS	256
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)   ECDH secp256r1 (eq. 3072 bits RSA)   FS	128
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (0xc028)   ECDH secp256r1 (eq. 3072 bits RSA)   FS   WEAK	256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (0xc027)   ECDH secp256r1 (eq. 3072 bits RSA)   FS   WEAK	128

**Comment by cyberwombat** [comment]
Ya that certificate will not work. You would need to find a cipher match (like TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) in the list of [supported](https://gist.github.com/cyberwombat/cba15f923c8e44bfa51f927323f8c670) ones.

I just tested a couple of sites - one with an Amazon cert (the ones you get when setting up CloudFront) as well as one from Let's Encrypt and they both work.  You have a WP site and both WPEngine (which I always recommend for WP sites) as well as Dreamhost offer WP hosting w free Let's Encrypt certificates.  It may be possible to ask for that certificate on your hosting - you would need to check with them.

**Comment by cyberwombat** [comment]
As far as a workaround - there is one. You need to disable SSL on your webhook route. I see that your site automatically redirects http to https so that would beed to be turned off - it can be enabled selectively on WP using some plugins so that your visitors do redirect but you can still access the webhook using http. That would get rid of the errors albeit without SSL. It's not much of a concern imo to have the webhook without ssl as all it does is send an order completion notice along with the secret to be checked which validates the webhook origin (assume you have set that up - it's optional).

**Comment by fantazo** [comment]
I have found this plugin:

https://wordpress.org/plugins/http-https-remover/

maybe it can do what you've said. I'll give a try.

**Comment by cyberwombat** [comment]
I am not sure that will do it - you want to be able to redirect http to https except for selected pages (the webhook) - perhaps this one https://wordpress.org/plugins/https-redirection/

**Comment by fantazo** [comment]
hmm I need to try a different one.
So to make it clear for me :) 

**1.** I need to find a plugin / solution to stop forcing my webhook address being redirected from http to https? Am i right?

**2.** after the webhook is not anymore with https and its using only http.. it should work with the fastspring webhook?

Thank you Yashua for taking your time and helping me and the community on Github.
I am pretty sure that are a lot of people who like your plugin!

**Comment by cyberwombat** [comment]
That's correct. Before you even try the plugins ensure that this will solve your problems.
So:
1. Disable http to https redirection on your site and ensure your site can be loaded with http.
2. Setup the HMAC SHA256 Secret if you have not done so as described in docs - this adds extra security to ensure your webhook cannot be forged. 
3. Change your webhook URL in the FS dashboard to use http protocol.
4. Test.
5. If successful try the WP plugin I listed (I have not used it but it seems to indicate that one can redirect all pages except selected ones). Redirect site to https ensuring the webhook route can still be accessed using http. 
6. Test again.
7. Profit :)

**Comment by fantazo** [comment]
I can’t disable https on https://fantazo-design.com/?wc-api=wc_gateway_fastspring
I've tried to disable from the server admin panel and delete chache ... not working.
I have used your plugin, but there is no option to disable on one page https redirect.

<img width="1507" alt="Screenshot 2019-08-14 at 03 06 10" src="https://user-images.githubusercontent.com/54009379/62985588-c1caf980-be40-11e9-97ba-4c50d752f00e.png">




---------------------
So I have googled and found this:

I have used this plugin:
https://wordpress.org/plugins/really-simple-ssl/

I have added this to .htaccess from this page:https://really-simple-ssl.com/knowledge-base/disabling-ssl-for-one-page-only/

```
# BEGIN rlrssslReallySimpleSSL rsssl_version[2.3.8]
<IfModule mod_rewrite.c>
RewriteEngine on
RewriteCond %{HTTPS} !=on [NC]
#this line may be different on other servers
RewriteCond %{REQUEST_URI} !/?wc-api=wc_gateway_fastspring #add your excluded page here
RewriteCond %{HTTP_HOST} ^fantazo-design.com [OR]
RewriteCond %{HTTP_HOST} ^www.fantazo-design.com
RewriteRule ^(.*)$ https://%{HTTP_HOST}%/$1 [R=301,L]
</IfModule>
# END rlrssslReallySimpleSSL
```

not working :(( what could i do?

**When I access the link =>>>** https://fantazo-design.com/?wc-api=wc_gateway_fastspring 
it gives me the -1 "error"

**Comment by fantazo** [comment]
What if we change the /?wc-api=wc_gateway_fastspring
 (<code>' . site_url('?wc-api=wc_gateway_fastspring', 'https') . '</code>) 
 (<code>' . site_url/**webhook**('?wc-api=wc_gateway_fastspring', '**http**') . '</code>) 

=> /webhook/?wc-api=wc_gateway_fastspring

And maybe this way we can give to the folder force / except https to http

**Comment by cyberwombat** [comment]
Well the first thing before anything is to turn off https from your panel. Make sure http://antazo-design.com doesn't redirect to https://fantazo-design.com

Once that is done then your webhook should work if you use http protocol when specifying it in your FS panel.

Then, once that is working you can redirect front to https. I looked at my notes because a previous user had same issue and this is what I suggested:

1. f you know how to modify the .htaccess file then you can follow these instructions https://webmasters.stackexchange.com/questions/77169/htaccess-force-https-except-one-page#77177

2. It’s also possible to put a JavaScript snippet in the head of your theme which is probably easier:
```
<script>
if (location.protocol != 'https:') {
 location.href = 'https:' + window.location.href.substring(window.location.protocol.length);
}
</script>
```
You can do so by going to Appearance > Editor and edit the header.php file.

I would still suggest using a different host as that's just a better solution but if you must use the one you have then one of the above should work.

**Comment by fantazo** [comment]
Hi again :)

This is what i have inserted into the .htaccess file



```
# BEGIN WordPress
<IfModule mod_rewrite.c>
		RewriteEngine On
# Go to https if not on room.html
RewriteCond %{SERVER_PORT} 80 
RewriteCond %{REQUEST_URI} !^/?wc-api=wc_gateway_fastspring$ [NC]
RewriteRule ^(.*)$ https://www.fantazo-design.com/$1 [R,L]

# Go to http if you are on room.html
RewriteCond %{SERVER_PORT} !80 
RewriteCond %{REQUEST_URI} ^/?wc-api=wc_gateway_fastspring$ [NC]
RewriteRule ^(.*)$ http://www.fantazo-design..com/$1 [R,L]
</IfModule>

# END WordPress
```


Did not worked, maybe there is still something that i need to add or not.
I have also inserted this into the header:

`<script>
if (location.protocol != 'https:') {
 location.href = 'https:' + window.location.href.substring(window.location.protocol.length);
}
</script>`


Unfortunately dis also not worked. I think I am doing something wrong in these codes that is why it not works :( do you have any suggestions ?

thank you :)

**Comment by cyberwombat** [comment]
Your website is still set to redirect to https. I cannot tell if its from your server settings or the code you added but did you get http://fantazo-design.com (without https) to work in the first place? That is the first thing you must achieve. The JS code or the htaccess are only to be used **after** you have successfully disabled the https redirection. 

So:
1. Remove the JS snippet and htaccess code for now
2. Ensure you can load http://fantazo-design.com (it should not redirect to https://fantazo-design.com)
3. Go to FastSpring and ensure your webhook url starts with http:// and not https:// 
4. Test. 

Only once that test is successful should you mess with the htaccess/snippet. These are only to redirect your frontend users to https without having all your pages redirect as they do now (including the webhook).
