### ISSUE TITLE
Regular payment works, but popup doesn't.

### ISSUE THREAD

**Issue by cyberwombat** [cyberwombat/woocommerce-fastspring-payment-gateway#21]
I have similar problem - regular payment works, but popup doesn't.

Everything is setup correctly. I can see access token included in code (I changed url and access key for privacy):

`<script type="text/javascript" id="fsc-api" data-storefront="mysite.onfastspring.com" data-before-requests-callback="fastspringBeforeRequestHandler" data-access-key="here-is-access-key-from-settings-matching-the-one-provided-by-fastspring" data-debug="true" data-test="yes" data-version="1.2.2" data-data-callback="dataCallbackFunction" data-error-callback="errorCallback" data-popup-closed="fastspringPopupCloseHandler" src="https://d1f8f9xcsvx3ha.cloudfront.net/sbl/0.7.6/fastspring-builder.min.js?ver=5.4"></script>`

And code for popup (got this form FS site):

```
<script id="fsc-api" src="https://d1f8f9xcsvx3ha.cloudfront.net/sbl/0.8.3/fastspring-builder.min.js" type="text/javascript" data-storefront="mysite.onfastspring.com/popup-mysite">
</script>
```

Domain is virtual localhost and it is whitelisted.

I get this error:
[FastSpring API] No access key found in payload.
[FastSpring API] (!) Error: Error received:  400 empty-session

WooCommerce status log is empty and test and logging is enabled in plugin settings...

_Originally posted by @kskrlinnorth2 in https://github.com/cyberwombat/woocommerce-fastspring-payment-gateway/issues/19#issuecomment-664998554_

**Comment by cyberwombat** [comment]
So you have two snippets going on. Don't add the one from FS. This is all handled by the plugin. Then ensure you are using the correct storefront in the settings - see [docs](https://github.com/cyberwombat/woocommerce-fastspring-payment-gateway/wiki/Plugin-installation#determining-your-storefront-path) in the section about using the popup and where to get storefront.  This plugin is using an older version of the FS script (0.7.6 instead of 0.8.3). If all works well I can bump the version and release a new plugin if you want to test it.

**Comment by kskrlinnorth2** [comment]
Yes, it works now. I didn't notice it is different storefront name for default and popup.

Thank you for fast response.

And yes, you can bump version and I will gladly test it.

**Comment by cyberwombat** [comment]
Cool. I just updated the beta release. Let me know how that works. Thanks!

https://github.com/cyberwombat/woocommerce-fastspring-payment-gateway/releases
