### ISSUE TITLE
Shipping price not working on Fastspring

### ISSUE THREAD

**Issue by rakesh535** [cyberwombat/woocommerce-fastspring-payment-gateway#22]
According to doc [https://fastspring.com/docs/shipping-fee-calculator](url). Product type should be Digital Product and Shipment or Physical Shipment, only then fastspring is able to calculate the shipping price. But in case of woocommerce product, it is not detecting the product type.

**Comment by cyberwombat** [comment]
This plugin is for woocommerce which means all products including shipping is managed by Woo - FastSpring is used as the payment gateway but the FastSpring store catalog is not used. You will want to use Woo shipping for this.

**Comment by rakesh535** [comment]
Please check the video https://www.loom.com/share/722201beffa84aad96ff95545b39a9a5

**Comment by cyberwombat** [comment]
As the plugin was developed for digital goods there is no support for shipping.One of the issues is that FS doesnt really understand non item fields so shipping cost would have to be applied and divided equally to each item in the cart.  Its something I can explore adding - had to do that with subscription fees - eventually.

**Comment by cyberwombat** [comment]
You could experiment with FS handling the shipping though there may be issues with the automatic reconciliation with Woo
