### ISSUE TITLE
New Product Tax Categories

### ISSUE THREAD

**Issue by peterStitt** [cyberwombat/woocommerce-fastspring-payment-gateway#23]
From October FastSpring wants all products defined to have a product tax category:
https://fastspring.com/docs/about-vat-and-sales-tax/
https://fastspring.com/docs/product-tax-category/

If I understand correctly, this plugin does not use the products that are defined in our FastSpring accounts and instead creates them on the fly for each order.

Does this new Product Tax Category have to be integrated in to the WooCommerce plugin or does nothing change? Will using this plugin still allow FastSpring to apply the appropriate taxes (software licenses) once things presumably move fully to the new system?

Thanks.

**Comment by cyberwombat** [comment]
Yes the products are indeed created on the fly - we use the [Store Builder library ](https://fastspring.com/docs/store-builder-library/) for this. I don't see options to pass tax category info in their docs (yet). FS is currently responsible for all the tax calculations - all the plugin does is send cost/qty of the items. I would presume FS has a default category for tax that it would fallback on for such dynamic scenarios. I'll see if any issues happen when they turn over to the new system and address that asap if so.
