### ISSUE TITLE
Integration with WooCommerce subscriptions

### ISSUE THREAD

**Issue by mediadigitalfacil** [cyberwombat/woocommerce-fastspring-payment-gateway#24]
Hello there,

I want to know if this plugin supports WooCommerce subscriptions? My concern is because I have a recurring paid membership business.

In case your answer is no, I would like to know if you can help me do this integration and how much would you charge me for doing it?

Thank you.

**Comment by cyberwombat** [comment]
Hi - there is subscription support - you can read more here https://github.com/cyberwombat/woocommerce-fastspring-payment-gateway/wiki/Subscriptions

**Comment by mediadigitalfacil** [comment]
Hello cyberwombat,

We have installed the plugin on our official live website and at the end of the purchase test, the system shows us a 404 error, and does not show the receipt page. I have recorded a short video for you to show you the process and the error. Please watch this video: https://www.loom.com/share/19ef4bd2aba942e49873ffb113642113

NOTE: this is a proof of purchase of a recurring paid membership in WooCommerce Subscriptions.

Could you please help us resolve this issue?

Thank you.

**Comment by cyberwombat** [comment]
It sounds like the plugin is not getting an order ID - hence the undefined.  The way it does this is by looking at the session for the `current_order`. 

I would try to enable all the debug options as outlined in wiki https://github.com/cyberwombat/woocommerce-fastspring-payment-gateway/wiki then try a regular purchase (not a subscription) and work on getting that working. Let me know if that is successful or not and we'll go from there. 

When you have debug enabled (there are two - one is the SCRIPT_DEBUG which will dump stuff to the console and the other is just logging info to the WooCommerce log which can be found in the WooCommerce Status section) look for anything that might be related to the missing session/order id.

**Comment by cyberwombat** [comment]
Additionally - what happens to the order in the admin? is the order there with an order #? did FS mark it as complete? or is there nothing at all?

**Comment by mediadigitalfacil** [comment]
First of all, I really appreciate your response.

I have set SCRIPT_DEBUG to true in the wp-config.php file and have activated Log debug messages in WooCommerce.

In this case, or I have programming knowledge and therefore, no errors can be identified in those files.

I have recorded a video for you with the results of a purchase of a joined payment product:
https://www.loom.com/share/5fd5a94dc9eb41dfb1de5642aafee791?from_recorder=1

thanks for your help

**Comment by cyberwombat** [comment]
Hmm it sounds like a permalink issue or potentially that something else is messing with the receipt url. I have added some debug statements to [this](https://gist.github.com/b3f3bc83ea6df45d080bb009cd51fab9) file - please replace the `includes/class-wc-gateway-fastspring-handler.php` with attached - run a transaction then look for any line that start with "DEBUG:" and paste that info.

**Comment by mediadigitalfacil** [comment]
Hello cyberwombat,

In my previous message I implied that I had programming knowledge, but it is not true, it was a spelling error.

Having clarified the above, I followed your instructions and replaced the file you told me, but now I don't know where to look for the information you require ("DEBUG:"). Could you please tell me where to look? What is the route that I should follow?

Thank you.

**Comment by cyberwombat** [comment]
Ah that would be in the log - WooCommerce > Status > Logs - look for the fastpring one. I think from a previous comment that you know where it's at - all I added was extra log statements that might shed some insight. I prefixed them with "DEBUG" to make it a bit easier.

**Comment by cyberwombat** [comment]
Also I am curious - does the receipt work with non FastSpring methods? You can turn on COD to make it easy to test a checkout.

**Comment by mediadigitalfacil** [comment]
I found the record of the proof of purchase we made yesterday, but can't find any lines that contain "DEBUG". Here below I am pasting the entire log record:

--------------------------------------------------------------

10-16-2020 @ 13:31:30 - Calculating pricing for amount of 997 and qty of 1 with cart total of 997 and discount of 0: 997
10-16-2020 @ 13:32:31 - is_valid_webhook_request: Checking FastSpring webhook validity
10-16-2020 @ 13:32:31 - Order tag found for 82779
10-16-2020 @ 13:32:34 - Marking order ID 82779 as complete
10-16-2020 @ 13:32:34 - {"id":"WvuRoMfNRFKaDGrJu4jsAA","processed":false,"created":1602847931509,"type":"order.completed","live":false,"data":{"order":"R3y41YYeQraooI3WK1TruQ","id":"R3y41YYeQraooI3WK1TruQ","reference":"MEDIADIGITALFAC201016-9174-14126","buyerReference":null,"ipAddress":"90.94.15.59","completed":true,"changed":1602847931441,"changedValue":1602847931441,"changedInSeconds":1602847931,"changedDisplay":"16\/10\/20","language":"es","live":false,"currency":"EUR","payoutCurrency":"USD","invoiceUrl":"https:\/\/mediadigitalfacil.onfastspring.com\/account\/order\/MEDIADIGITALFAC201016-9174-14126\/invoice","account":"AV1cMnF1QgSy1l0MHYzRCg","total":1066,"totalDisplay":"1.066,00\u00a0\u20ac","totalInPayoutCurrency":1205.640000000000100044417195022106170654296875,"totalInPayoutCurrencyDisplay":"1.205,64\u00a0US$","tax":185.009999999999990905052982270717620849609375,"taxDisplay":"185,01\u00a0\u20ac","taxInPayoutCurrency":209.240000000000009094947017729282379150390625,"taxInPayoutCurrencyDisplay":"209,24\u00a0US$","subtotal":880.990000000000009094947017729282379150390625,"subtotalDisplay":"880,99\u00a0\u20ac","subtotalInPayoutCurrency":996.3899999999999863575794734060764312744140625,"subtotalInPayoutCurrencyDisplay":"996,39\u00a0US$","discount":0,"discountDisplay":"0,00\u00a0\u20ac","discountInPayoutCurrency":0,"discountInPayoutCurrencyDisplay":"0,00\u00a0US$","discountWithTax":0,"discountWithTaxDisplay":"0,00\u00a0\u20ac","discountWithTaxInPayoutCurrency":0,"discountWithTaxInPayoutCurrencyDisplay":"0,00\u00a0US$","billDescriptor":"FS* mediadigitalfac","payment":{"type":"test","cardEnding":"4242"},"customer":{"first":"Pedro","last":"Tes1","email":"tes1@tes1.com","company":null,"phone":"000000000","subscribed":false},"address":{"country":"ES","display":"ES"},"recipients":[{"recipient":{"first":"Pedro","last":"Tes1","email":"tes1@tes1.com","company":null,"phone":"000000000","subscribed":false,"account":"AV1cMnF1QgSy1l0MHYzRCg","address":{"country":"ES","display":"ES"}}}],"tags":{"store_order_id":82779},"notes":[],"items":[{"product":"media-digital-facil-plan-vitalicio","quantity":1,"display":"Media Digital F\u00e1cil - Plan Vitalicio","sku":null,"imageUrl":null,"subtotal":880.990000000000009094947017729282379150390625,"subtotalDisplay":"880,99\u00a0\u20ac","subtotalInPayoutCurrency":996.3899999999999863575794734060764312744140625,"subtotalInPayoutCurrencyDisplay":"996,39\u00a0US$","discount":0,"discountDisplay":"0,00\u00a0\u20ac","discountInPayoutCurrency":0,"discountInPayoutCurrencyDisplay":"0,00\u00a0US$","fulfillments":{}}]}}
10-16-2020 @ 19:07:07 - Calculating pricing for amount of 997 and qty of 1 with cart total of 997 and discount of 0: 997
10-16-2020 @ 19:08:21 - is_valid_webhook_request: Checking FastSpring webhook validity
10-16-2020 @ 19:08:21 - Order tag found for 82790
10-16-2020 @ 19:08:24 - Marking order ID 82790 as complete
10-16-2020 @ 19:08:24 - {"id":"jabasMI7QhOp53HmpEeWKA","processed":false,"created":1602868072502,"type":"order.completed","live":false,"data":{"order":"nrmIzAdDQneyCSOrnMuRMg","id":"nrmIzAdDQneyCSOrnMuRMg","reference":"MEDIADIGITALFAC201016-9037-69108","buyerReference":null,"ipAddress":"90.94.15.59","completed":true,"changed":1602868072443,"changedValue":1602868072443,"changedInSeconds":1602868072,"changedDisplay":"16\/10\/20","language":"es","live":false,"currency":"EUR","payoutCurrency":"USD","invoiceUrl":"https:\/\/mediadigitalfacil.onfastspring.com\/account\/order\/MEDIADIGITALFAC201016-9037-69108\/invoice","account":"FtkZ7wESTyGQoqtC4fsxMQ","total":1066,"totalDisplay":"1.066,00\u00a0\u20ac","totalInPayoutCurrency":1205.640000000000100044417195022106170654296875,"totalInPayoutCurrencyDisplay":"1.205,64\u00a0US$","tax":185.009999999999990905052982270717620849609375,"taxDisplay":"185,01\u00a0\u20ac","taxInPayoutCurrency":209.240000000000009094947017729282379150390625,"taxInPayoutCurrencyDisplay":"209,24\u00a0US$","subtotal":880.990000000000009094947017729282379150390625,"subtotalDisplay":"880,99\u00a0\u20ac","subtotalInPayoutCurrency":996.3899999999999863575794734060764312744140625,"subtotalInPayoutCurrencyDisplay":"996,39\u00a0US$","discount":0,"discountDisplay":"0,00\u00a0\u20ac","discountInPayoutCurrency":0,"discountInPayoutCurrencyDisplay":"0,00\u00a0US$","discountWithTax":0,"discountWithTaxDisplay":"0,00\u00a0\u20ac","discountWithTaxInPayoutCurrency":0,"discountWithTaxInPayoutCurrencyDisplay":"0,00\u00a0US$","billDescriptor":"FS* mediadigitalfac","payment":{"type":"test","cardEnding":"4242"},"customer":{"first":"Pedro","last":"Ariza55","email":"ariza55@ariza55.com","company":null,"phone":"000000000","subscribed":false},"address":{"country":"ES","display":"ES"},"recipients":[{"recipient":{"first":"Pedro","last":"Ariza55","email":"ariza55@ariza55.com","company":null,"phone":"000000000","subscribed":false,"account":"FtkZ7wESTyGQoqtC4fsxMQ","address":{"country":"ES","display":"ES"}}}],"tags":{"store_order_id":82790},"notes":[],"items":[{"product":"media-digital-facil-plan-vitalicio","quantity":1,"display":"Media Digital F\u00e1cil - Plan Vitalicio","sku":null,"imageUrl":null,"subtotal":880.990000000000009094947017729282379150390625,"subtotalDisplay":"880,99\u00a0\u20ac","subtotalInPayoutCurrency":996.3899999999999863575794734060764312744140625,"subtotalInPayoutCurrencyDisplay":"996,39\u00a0US$","discount":0,"discountDisplay":"0,00\u00a0\u20ac","discountInPayoutCurrency":0,"discountInPayoutCurrencyDisplay":"0,00\u00a0US$","fulfillments":{}}]}}

--------------------------------------------------------------

**Comment by mediadigitalfacil** [comment]
When you say: "turn on COD". You mean Cash on Delivery?

**Comment by cyberwombat** [comment]
yes COD is a great way to test out a checkout since you just click done - no need for credit card numbers etc..

So its a bit odd that there is no DEBUG lines - can you ensure the correct file got updated? I see a log line that comes right after one of my DEBUG lines which makes me think the updated file did not take for some reason. I added some changes so do regrab the code I sent and make that a file called `class-wc-gateway-fastspring-handler.php` and replace the one in the `includes` folder and try again.   Just before the line "Marking order ID ... as complete" you should see "DEBUG: Generating receipt for order ...". If you don't then perhaps try disabling/reenabling plugin

**Comment by mediadigitalfacil** [comment]
Dear cyberwombat,

I let you know that we have made 3 purchase tests. I put them here below in the order we made them.

NOTE: I must clarify that we make sure to replace the file that you indicated with the new code that you made to review the DEBUG.

The first test was with the COD option, in which the purchase receipt is shown. Please watch this video: https://www.loom.com/share/ff06a030248d48cda2866e98c25ce22a

The second test was via FastSpring, where the result was the same. WooCommerce logs got an error again, but nothing that starts with DEBUG still appears. Below the video I put the error code. Please watch this second video: https://www.loom.com/share/3370cc2e90fb4105b065e0d7cee8a32c

---------------------------------------------------------------------

10-19-2020 @ 20:17:41 - Calculating pricing for amount of 997 and qty of 1 with cart total of 997 and discount of 0: 997
10-19-2020 @ 20:20:25 - is_valid_webhook_request: Checking FastSpring webhook validity
10-19-2020 @ 20:20:25 - Order tag found for 82862
10-19-2020 @ 20:20:27 - Marking order ID 82862 as complete
10-19-2020 @ 20:20:27 - {"id":"q2yPGIvsRAOjNM9oa-MJHw","processed":false,"created":1603131579117,"type":"order.completed","live":false,"data":{"order":"Hc0KGR63SnyMbICCNh90yQ","id":"Hc0KGR63SnyMbICCNh90yQ","reference":"MEDIADIGITALFAC201019-9174-11115","buyerReference":null,"ipAddress":"90.94.15.59","completed":true,"changed":1603131579043,"changedValue":1603131579043,"changedInSeconds":1603131579,"changedDisplay":"19\/10\/20","language":"es","live":false,"currency":"EUR","payoutCurrency":"USD","invoiceUrl":"https:\/\/mediadigitalfacil.onfastspring.com\/account\/order\/MEDIADIGITALFAC201019-9174-11115\/invoice","account":"nAY9ZXL0SLeb39eiD116Pg","total":1067,"totalDisplay":"1.067,00\u00a0\u20ac","totalInPayoutCurrency":1206.920000000000072759576141834259033203125,"totalInPayoutCurrencyDisplay":"1.206,92\u00a0US$","tax":185.18000000000000682121026329696178436279296875,"taxDisplay":"185,18\u00a0\u20ac","taxInPayoutCurrency":209.460000000000007958078640513122081756591796875,"taxInPayoutCurrencyDisplay":"209,46\u00a0US$","subtotal":881.8200000000000500222085975110530853271484375,"subtotalDisplay":"881,82\u00a0\u20ac","subtotalInPayoutCurrency":997.4600000000000363797880709171295166015625,"subtotalInPayoutCurrencyDisplay":"997,46\u00a0US$","discount":0,"discountDisplay":"0,00\u00a0\u20ac","discountInPayoutCurrency":0,"discountInPayoutCurrencyDisplay":"0,00\u00a0US$","discountWithTax":0,"discountWithTaxDisplay":"0,00\u00a0\u20ac","discountWithTaxInPayoutCurrency":0,"discountWithTaxInPayoutCurrencyDisplay":"0,00\u00a0US$","billDescriptor":"FS* mediadigitalfac","payment":{"type":"test","cardEnding":"4242"},"customer":{"first":"Pedro","last":"Ariza147","email":"ariza147@ariza147.com","company":null,"phone":"000000000","subscribed":false},"address":{"country":"ES","display":"ES"},"recipients":[{"recipient":{"first":"Pedro","last":"Ariza147","email":"ariza147@ariza147.com","company":null,"phone":"000000000","subscribed":false,"account":"nAY9ZXL0SLeb39eiD116Pg","address":{"country":"ES","display":"ES"}}}],"tags":{"store_order_id":82862},"notes":[],"items":[{"product":"media-digital-facil-plan-vitalicio","quantity":1,"display":"Media Digital F\u00e1cil - Plan Vitalicio","sku":null,"imageUrl":null,"subtotal":881.8200000000000500222085975110530853271484375,"subtotalDisplay":"881,82\u00a0\u20ac","subtotalInPayoutCurrency":997.4600000000000363797880709171295166015625,"subtotalInPayoutCurrencyDisplay":"997,46\u00a0US$","discount":0,"discountDisplay":"0,00\u00a0\u20ac","discountInPayoutCurrency":0,"discountInPayoutCurrencyDisplay":"0,00\u00a0US$","fulfillments":{}}]}}
10-19-2020 @ 20:31:48 - Calculating pricing for amount of 997 and qty of 1 with cart total of 997 and discount of 0: 997
10-19-2020 @ 20:32:21 - is_valid_webhook_request: Checking FastSpring webhook validity
10-19-2020 @ 20:32:21 - Order tag found for 82863
10-19-2020 @ 20:32:24 - Marking order ID 82863 as complete
10-19-2020 @ 20:32:24 - {"id":"x6VLhinUTRSlNVJszFNbMQ","processed":false,"created":1603132335760,"type":"order.completed","live":false,"data":{"order":"zYYPVc3tRKWg4B3gynosfA","id":"zYYPVc3tRKWg4B3gynosfA","reference":"MEDIADIGITALFAC201019-9037-57130","buyerReference":null,"ipAddress":"90.94.15.59","completed":true,"changed":1603132335710,"changedValue":1603132335710,"changedInSeconds":1603132335,"changedDisplay":"19\/10\/20","language":"es","live":false,"currency":"EUR","payoutCurrency":"USD","invoiceUrl":"https:\/\/mediadigitalfacil.onfastspring.com\/account\/order\/MEDIADIGITALFAC201019-9037-57130\/invoice","account":"R8jdYRu4S1GrjEF_LHngUg","total":1067,"totalDisplay":"1.067,00\u00a0\u20ac","totalInPayoutCurrency":1206.920000000000072759576141834259033203125,"totalInPayoutCurrencyDisplay":"1.206,92\u00a0US$","tax":185.18000000000000682121026329696178436279296875,"taxDisplay":"185,18\u00a0\u20ac","taxInPayoutCurrency":209.460000000000007958078640513122081756591796875,"taxInPayoutCurrencyDisplay":"209,46\u00a0US$","subtotal":881.8200000000000500222085975110530853271484375,"subtotalDisplay":"881,82\u00a0\u20ac","subtotalInPayoutCurrency":997.4600000000000363797880709171295166015625,"subtotalInPayoutCurrencyDisplay":"997,46\u00a0US$","discount":0,"discountDisplay":"0,00\u00a0\u20ac","discountInPayoutCurrency":0,"discountInPayoutCurrencyDisplay":"0,00\u00a0US$","discountWithTax":0,"discountWithTaxDisplay":"0,00\u00a0\u20ac","discountWithTaxInPayoutCurrency":0,"discountWithTaxInPayoutCurrencyDisplay":"0,00\u00a0US$","billDescriptor":"FS* mediadigitalfac","payment":{"type":"test","cardEnding":"4242"},"customer":{"first":"Pedro","last":"Ariza148","email":"ariza148@ariza148.com","company":null,"phone":"000000000","subscribed":false},"address":{"country":"ES","display":"ES"},"recipients":[{"recipient":{"first":"Pedro","last":"Ariza148","email":"ariza148@ariza148.com","company":null,"phone":"000000000","subscribed":false,"account":"R8jdYRu4S1GrjEF_LHngUg","address":{"country":"ES","display":"ES"}}}],"tags":{"store_order_id":82863},"notes":[],"items":[{"product":"media-digital-facil-plan-vitalicio","quantity":1,"display":"Media Digital F\u00e1cil - Plan Vitalicio","sku":null,"imageUrl":null,"subtotal":881.8200000000000500222085975110530853271484375,"subtotalDisplay":"881,82\u00a0\u20ac","subtotalInPayoutCurrency":997.4600000000000363797880709171295166015625,"subtotalInPayoutCurrencyDisplay":"997,46\u00a0US$","discount":0,"discountDisplay":"0,00\u00a0\u20ac","discountInPayoutCurrency":0,"discountInPayoutCurrencyDisplay":"0,00\u00a0US$","fulfillments":{}}]}}

---------------------------------------------------------------------

In the third test we followed your final instructions, that is, we deactivated the plugin and then we activated it again. Then we did the proof of purchase, but this time no error was generated in the WooCommerce logs. Please watch this third video: https://www.loom.com/share/fe6bced1aac243aa9034c7dc92f89192

**Comment by mediadigitalfacil** [comment]
Additionally we received a notification from FastSpring, related to a webhook failure on the test site where we first ran some tests. Here I paste the message:

MESSAGE SUBJECT: 
Tienda de Media Digital Facil webhook events failure https://staging2.mediadigitalfacil.com/?wc-api=wc_gateway_fastspring - 10/19/2020 18:30:10, UTC

MESSAGE BODY:
`Webhook events to https://staging2.mediadigitalfacil.com/?wc-api=wc_gateway_fastspring were not successfully delivered.

{"status":504,"statusText":"Gateway Timeout","headers":{"Server":"nginx","Date":"Mon, 19 Oct 2020 18:20:23 GMT","Content-Type":"text/html; charset=iso-8859-1","Content-Length":"247","Connection":"keep-alive"},"body":"<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>504 Gateway Timeout</title>\n</head><body>\n<h1>Gateway Timeout</h1>\n<p>The gateway did not receive a timely response\nfrom the upstream server or application.</p>\n</body></html>\n"}

Regular attempts will be made to deliver events for the next 24 hours. Events not delivered after 24 hours will be removed from the queue.

Use "/events" API endpoint to retrieve failed webhook events after 24 hours – http://docs.fastspring.com/integrating-with-fastspring/fastspring-api/events

If you need further assistance, please submit support request via the support link in the control panel.
`

**Comment by cyberwombat** [comment]
Very odd - I just tested with the debug file and it is adding the DEBUG line in mine - didnt need to reload.  Please keep tryong to get the DEBUG lines to show as its hard to determine otherwise.

Also - when you go to YOURSITE/wp-admin/admin.php?page=wc-settings&tab=advanced - under "Checkout endpoints" is there something filled in in all the fields especially the one called "Order received"?

Send me the version of Woo, Subscriptions and WP and I will see if there is some issue there. Also try disabling all the plugins you can - including subscriptions - we want to get the basic purchase working

**Comment by mediadigitalfacil** [comment]
That's right, something weird is happening, because we've done a lot of tests and no matter how hard we try, we can't get the DEBUG lines to appear.

At this point we don't know if we are not doing something right. For this reason, we think it will be best if you personally do some tests on our test site. It is a "staging site", literally a clone of our official site.

Could you please let us know how we can privately send you the login access to our test site?

NOTE 1: in the option "Checkout endpoints", there is no missing field to complete. See screenshot: https://prnt.sc/v3jjfy

NOTE 2: We deactivated most of the plugins as you advised, but the results were the same.

I await for your answer to give you the login access to our test site.

Thank you.

**Comment by cyberwombat** [comment]
you can send to contact@enradia.com. I am traveling this week so might be a little slow looking at things but will do what I can.

**Comment by mediadigitalfacil** [comment]
I already sent you the login credentials. The sender is: Alex Alvarez.

The subject of the message is: Here are the login data for Media Digital Facil
