### ISSUE TITLE
Fatal Error 

### ISSUE THREAD

**Issue by JaniKervinen** [cyberwombat/woocommerce-fastspring-payment-gateway#26]
Hi,

Here is an issue I'm experiencing with FastSpring Gateway (this is fatal errors log from woocommerce settings):

2021-01-06T04:25:45+00:00 CRITICAL Uncaught Error: Call to a member function get_id() on bool in /www/onlinestorelegacy_334/public/assets/plugins/woocommerce-fastspring-payment-gateway/includes/class-wc-gateway-fastspring-handler.php:110
Stack trace:
#0 /www/onlinestorelegacy_334/public/wp-includes/class-wp-hook.php(287): WC_Gateway_FastSpring_Handler->ajax_get_receipt('')
#1 /www/onlinestorelegacy_334/public/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#2 /www/onlinestorelegacy_334/public/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /www/onlinestorelegacy_334/public/assets/plugins/woocommerce/includes/class-wc-ajax.php(90): do_action('wc_ajax_wc_fast...')
#4 /www/onlinestorelegacy_334/public/wp-includes/class-wp-hook.php(287): WC_AJAX::do_wc_ajax('')
#5 /www/onlinestorelegacy_334/public/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(false, Array)
#6 /www/onlinestorelegacy_334/public/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#7 /www/onlinestorelegacy_334/public/wp-includes/template in /www/onlinestorelegacy_334/public/assets/plugins/woocommerce-fastspring-payment-gateway/includes/class-wc-gateway-fastspring-handler.php on line 110

**Comment by cyberwombat** [comment]
Closing and continuing convo on https://github.com/cyberwombat/woocommerce-fastspring-payment-gateway/issues/27
