### ISSUE TITLE
Adding subscription products to cart works, checkout does not

### ISSUE THREAD

**Issue by JaniKervinen** [cyberwombat/woocommerce-fastspring-payment-gateway#27]
Hey,

I have three subscription products in my store and they are not working with the gateway. Cart page works fine, but once I or customers hit "proceed to checkout", there is a woocommerce error message:

"There are some issues with the items in your cart. Please go back to the cart page and resolve these issues before checking out."

Woocommerce is latest version to date

**Comment by cyberwombat** [comment]
The error from your other issue stems from the fact that Woo cannot find an order.  The message above doesn't seem related to the checkout process - I suspect you have an issue with the subscription plugin. Can you provide the name and version of the subscription plugin as well as the version of woo and wp please.

**Comment by JaniKervinen** [comment]
I'm using these plugins with their latest version available:

WooCommerce Subscriptions: https://woocommerce.com/products/woocommerce-subscriptions/
WooCommerce All Products for subscription: https://woocommerce.com/products/all-products-for-woocommerce-subscriptions/
WooCommerce Mix and Match products: https://woocommerce.com/products/woocommerce-mix-and-match-products/

You can check the product page example here: https://www.mysteryislands-music.com/product/custom-bundle-3/

**Comment by cyberwombat** [comment]
The error "There are some issues with the items in your cart. Please go back to the cart page and resolve these issues before checking out" is a woocommerce thing, I would disable fastspring - use COD for testing for example - and get that error to go away. FastSpring doesn't really come into play until the checkout page is loaded.  Let me know if error is still there with FS disabled.

**Comment by JaniKervinen** [comment]
Oh yes ok, I will test that out to see if it resolves the issue.
I'm not sure why this started to happen out of the blue after taking the FastSpring payment gateway in use.

I'll report back shortly. Great plug-in 👍🏻

**Comment by JaniKervinen** [comment]
the issue was indeed outside the gateway plugin. I was able to track it down to "XT Plugins Woo Add To Cart" plugin. By disabling the Ajax Add to cart, everything started to work again.

Sorry for bugging out.
