### ISSUE TITLE
Gateway creates new order each time, even if the same cart is submitted.

### ISSUE THREAD

**Issue by ps-PKrueger** [cyberwombat/woocommerce-fastspring-payment-gateway#7]
I am not sure if this is related to the pending payment issue, or not.
The gateway is creating a new order each time, even if the same order is submitted, and then cancelled.

For example:  I put an item in the cart, and select pay for order.  The Fastspring window shows up, and I close the window without paying.  This creates a pending order.

I click on the pay for order button again, the Fastspring window shows up again, and another separate pending order is created.

I don't believe that this was the behavior of the last version, but I haven't tested that yet.

**Comment by cyberwombat** [comment]
I am not able to recreate this. If you set SCRIPT_DEBUG to true (see wiki if questions) then it will use the non minified `fastspring-checkout.js` which will dump the unencrypted payload to console (also info on wiki) - I get a line `store_order_id` which seems to stay consistent as I close/open window. 
![screen shot 2018-06-03 at 8 57 17 am](https://user-images.githubusercontent.com/777498/40888459-34961518-670c-11e8-8c39-2240504a982e.png)

**Comment by ps-PKrueger** [comment]
I will pull your latest code and apply it.  Maybe this was an artifact of Version 1.1.1.  I will be testing more today, and will update as soon as I get results.

**Comment by ps-PKrueger** [comment]
This was an artifact of 1.1.1. This is operating as it should now.
